version: "3.6"
volumes:
  shared-workspace:
    name: "shared-workspace"
    driver: local
services:
  java-container:
    image: java_image
    container_name: java-container
    networks:
      - odp_intra_network
    volumes:
      - /Users/vyshnavi/Documents/GitHub/kafka-java/:/java-ex/kafka-java
      - shared-workspace:/opt/spark/shared-workspace
networks:
  odp_intra_network:
    external: true